# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

minimum_prek_version = "0.4.0"

[[repos]]
repo = "builtin"
hooks = [
  { id = "check-case-conflict" },
  { id = "check-merge-conflict" },
  { id = "check-toml" },
  { id = "end-of-file-fixer" },
  { id = "mixed-line-ending" },
  { id = "pretty-format-json" },
  { id = "trailing-whitespace" },
]

[[repos]]
repo = "https://github.com/codespell-project/codespell"
rev = "v2.4.3"
hooks = [{ id = "codespell" }]

[[repos]]
repo = "https://github.com/DavidAnson/markdownlint-cli2"
rev = "v0.23.1"
hooks = [{ id = "markdownlint-cli2" }]
