name = "Set slim image"
description = "Use the slim image version to get a smaller target image with fewer packages and a reduced attack surface."

[debian]
negative = "FROM debian:13.6"
positive = """
ARG DEBIAN_VERSION=13.6

FROM debian:${DEBIAN_VERSION}-slim
"""

[alpine]
negative = "..."
positive = """
ARG ALPINE_TAG=3.24.1

FROM alpine:${ALPINE_TAG}
"""
