name = "Set slim image"
description = "Use the slim image version to get a smaller target image with fewer packages and a reduced attack surface."

[debian]
negative = "FROM debian:13.6"
positive = "FROM debian:13.6-slim"

[alpine]
negative = "..."
positive = "FROM alpine:3.24.1"
