name = "Set SHA-256 digest using image"
description = "To ensure reproducibility of the build, as tags may appear in different images."
skill = "dockerfile-skills"

[debian]
negative = "FROM debian:13.6-slim"
positive = """
ARG DEBIAN_VERSION=13.6

FROM debian:${DEBIAN_VERSION}-slim@sha256:020c0d20b9880058cbe785a9db107156c3c75c2ac944a6aa7ab59f2add76a7bd
"""

[alpine]
negative = "FROM alpine:3.24.1"
positive = """
ARG ALPINE_VERSION=3.24.1

FROM alpine:${ALPINE_VERSION}@sha256:28bd5fe8b56d1bd048e5babf5b10710ebe0bae67db86916198a6eec434943f8b
"""
