name = "Set own mirrors for packages"
description = "Override mirrors to fetch packages from faster/more reliable sources (local mirror, proxy, cache)."

[debian]
negative = "..."
positive = """
ARG DEBIAN_CODENAME=trixie
ARG DEBIAN_MIRROR=http://deb.debian.org/debian

RUN \\
    rm -rf /etc/apt/sources.list /etc/apt/sources.list.d && \\
    mkdir -p /etc/apt/sources.list.d && \\
    { \\
    echo "Types: deb" ; \\
    echo "URIs: ${DEBIAN_MIRROR}/" ; \\
    echo "Suites: ${DEBIAN_CODENAME}" ; \\
    echo "Components: main non-free contrib non-free-firmware" ; \\
    echo "Signed-By: /usr/share/keyrings/debian-archive-keyring.pgp" ; \\
    echo ; \\
    echo "Types: deb" ; \\
    echo "URIs: ${DEBIAN_MIRROR}/" ; \\
    echo "Suites: ${DEBIAN_CODENAME}-updates" ; \\
    echo "Components: main non-free contrib non-free-firmware" ; \\
    echo "Signed-By: /usr/share/keyrings/debian-archive-keyring.pgp" ; \\
    echo ; \\
    echo "Types: deb" ; \\
    echo "URIs: ${DEBIAN_MIRROR}-security/" ; \\
    echo "Suites: ${DEBIAN_CODENAME}-security" ; \\
    echo "Components: main non-free contrib non-free-firmware" ; \\
    echo "Signed-By: /usr/share/keyrings/debian-archive-keyring.pgp" ; \\
    } > /etc/apt/sources.list.d/mirror.sources
"""

[alpine]
negative = "..."
positive = """
ARG ALPINE_VERSION=v3.24
ARG ALPINE_MIRROR=https://dl-cdn.alpinelinux.org/alpine

RUN \\
    { \\
    echo "${ALPINE_MIRROR}/${ALPINE_VERSION}/main" ; \\
    echo "${ALPINE_MIRROR}/${ALPINE_VERSION}/community" ; \\
    } > /etc/apk/repositories
"""
