name = "Set own mirrors for packages"
description = "Override mirrors to fetch packages from faster/more reliable sources (local mirror, proxy, cache)."

[debian]
negative = "..."
positive = """
ARG SUITE=trixie
ARG MIRROR_DEBIAN=http://deb.debian.org/debian

RUN \\
    rm -rf /etc/apt/sources.list /etc/apt/sources.list.d && \\
    mkdir -p /etc/apt/sources.list.d && \\
    { \\
    echo "Types: deb" ; \\
    echo "URIs: ${MIRROR_DEBIAN}/" ; \\
    echo "Suites: ${SUITE}" ; \\
    echo "Components: main non-free contrib non-free-firmware" ; \\
    echo "Signed-By: /usr/share/keyrings/debian-archive-keyring.pgp" ; \\
    echo ; \\
    echo "Types: deb" ; \\
    echo "URIs: ${MIRROR_DEBIAN}/" ; \\
    echo "Suites: ${SUITE}-updates" ; \\
    echo "Components: main non-free contrib non-free-firmware" ; \\
    echo "Signed-By: /usr/share/keyrings/debian-archive-keyring.pgp" ; \\
    echo ; \\
    echo "Types: deb" ; \\
    echo "URIs: ${MIRROR_DEBIAN}-security/" ; \\
    echo "Suites: ${SUITE}-security" ; \\
    echo "Components: main non-free contrib non-free-firmware" ; \\
    echo "Signed-By: /usr/share/keyrings/debian-archive-keyring.pgp" ; \\
    } > /etc/apt/sources.list.d/mirror.sources
"""

[alpine]
negative = "..."
positive = """
ARG VERSION=v3.24
ARG MIRROR_ALPINE=https://dl-cdn.alpinelinux.org/alpine

RUN \\
    { \\
    echo "${MIRROR_ALPINE}/${VERSION}/main" ; \\
    echo "${MIRROR_ALPINE}/${VERSION}/community" ; \\
    } > /etc/apk/repositories
"""
